# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-23 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_cartinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstype',
            options={'verbose_name': '商品類型', 'verbose_name_plural': '商品類型'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='goodsType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType', verbose_name='商品類型'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/upload/goods', verbose_name='商品圖片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品價格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=40, verbose_name='商品名稱'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='desc',
            field=models.TextField(null=True, verbose_name='類型描述'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/upload/goodstype', verbose_name='類型圖片'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='title',
            field=models.CharField(max_length=20, verbose_name='類型標題'),
        ),
    ]
