# Generated by Django 2.2.10 on 2020-02-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200123_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartinfo',
            options={'verbose_name': '購物車', 'verbose_name_plural': '購物車'},
        ),
    ]
