# Generated by Django 2.2.10 on 2020-02-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20200206_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstype',
            options={'verbose_name': '商品類型ok', 'verbose_name_plural': '商品類型ok'},
        ),
    ]
