# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-09 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20200206_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstype',
            options={'verbose_name': '商品類型', 'verbose_name_plural': '商品類型'},
        ),
    ]
